### ISSUE TITLE
Job Splitter Mod

### ISSUE THREAD

**Issue by peter233** [HaploX1/RimWorld-Miscellaneous_Mods#1]
Es gibt Probleme mit der Job Splitter Mod und den Robots. Die erledigen manche Jobs nicht wenn man Job Splitter Mod installiert hat. Wie Drill oder Pods beladen.

**Comment by HaploX1** [comment]
This is more a problem from the Job Splitter Mod and I think it is fixed now.
Thanks for the info though.
