### ISSUE TITLE
Combat Extended compatibility for Misc TurretBase

### ISSUE THREAD

**Issue by perkinslr** [HaploX1/RimWorld-Miscellaneous_Mods#12]
I'm one of the C# devs for Combat Extended, and would like to make CE firearms work with the modular turret.  I've done this before as a standalone mod, but it was rather brittle.  I can roll the changes needed into CE (need to subclass `Building_TurretWeaponBase` and probably do some reflection), but I think they can be done more easily from your side (need to conditionally add a few Gizmos).  If I send you a diff to support CE from your side, would you use it?  It would add CombatExtended as a compile-time (but not run-time) dependency.

**Comment by perkinslr** [comment]
I just found you have the source in a separate repo, I can open an issue there if you prefer.

**Comment by HaploX1** [comment]
Sorry for the long delay, I'm not often on Git..
If you have a something that can be added to the CE patch, I'm always welcome you for it :)
I'm (as always) a bit short on modding time, but I'll definitely try to incorporate it. Just not into the main mod, as I try to leave them mod independent, but in the CE patch mods.

**Comment by perkinslr** [comment]
Looks like you already have a subclass of `Building_TurretWeaponBase` in the CE patch, so that should work passably well.  The main issue that creates is if you need a different subclass to support *another* mod at the same time, you'll hit a wall.  

Anyway, I'll see about making a pull request against the source repo when I have the new CE API for turrets ready to use.

**Comment by perkinslr** [comment]
Alright, I opened a PR on the other repo.
