### ISSUE TITLE
cannot activate MAI?

### ISSUE THREAD

**Issue by Bia10** [HaploX1/RimWorld-Miscellaneous_Mods#13]
hi there, nice mods 

i dunno if its due to incompatibility or bug, but it seems i cannot activate MAI, the task gets done resources eaten but nuthin happens :/

![screenshot8](https://user-images.githubusercontent.com/2548763/95683667-fffead00-0bec-11eb-86af-f3fd659ed0e9.png)

**Comment by HaploX1** [comment]
Did you update to the latest version? 
There was an incompatibility with 1.2 that should now be fixed.
If you did update already, please provide me some error log.
Thank you very much.
