### ISSUE TITLE
Miscellaneous_Robots Stay and dont working

### ISSUE THREAD

**Issue by Anymorf** [HaploX1/RimWorld-Miscellaneous_Mods#16]
On Version 1.1 Robots after activation do nothing. they stay on their stations.
![Безымянный](https://user-images.githubusercontent.com/60013150/124377575-35848280-dcb5-11eb-98af-9079f3048317.png)
It happens with other mods and standalone only
now loaded:
Harmony
Core 
Royalty
HugsLib
Misc. core & mods
[Player.log](https://github.com/HaploX1/RimWorld-Miscellaneous_Mods/files/6759700/Player.log)

Mai works

**Comment by HaploX1** [comment]
If they stay and do nothing, than it is not build against the correct version of RimWorld.
As this is 1.1 and we're close to 1.3 I will not fix this issue, sorry. You should update to a newer version.
