### ISSUE TITLE
MAI, activating a mai give me the AIPawn_AIPawnCreator instead of activating it

### ISSUE THREAD

**Issue by ArliArdevlirn** [HaploX1/RimWorld-Miscellaneous_Mods#18]
When trying to activate a MAI at the end of the activation bill my colonist will receive an AIPawn_AIPawnCreator item that they will go store in stockpile(item hard to notice since there is only the wooden crate like when structure are being turned into item) instead of having the MAI activate.
That item then must be selected and given order to be placed for colonist to place it which will spawn a MAi and delete the inactive body used to create the AIPawn_AIPawnCreator.
Also no error is thrown into the log.

**Comment by HaploX1** [comment]
The PawnCreator is a little helper that creates the MAI.
Normally that should spawn and selfdestruct automatically, I have no idea why it doesn't do that for you.
Unfortunately I've also abandoned/postponed MAI for 1.4 so I will not work on it right now.
