### ISSUE TITLE
Mai Creator, female

### ISSUE THREAD

**Issue by firefoxpdm** [HaploX1/RimWorld-Miscellaneous_Mods#8]
When trying to activate a MAI, a "Mai Creator, female" object is created and put next to the activator character instead of the MAI being activated. This has happened already three times. It has also succeeded twice. There are no messages on the console. Issue is reproducible when only the base mods are loaded:

Harmony
Core (1.1.2570)
Royalty
Misc CORE
Misc MAI

Mods are the latest versions.

![image](https://user-images.githubusercontent.com/2911221/76794433-4b6fea80-67c7-11ea-95bd-599643e16726.png)

Expectation:
The MAI is automatically activated once the crafting bill is finished, without a "Mai Creator" object being created.

Workaround:
The "Mai Creator, female" has an Install gizmo through which the MAI can be activated.

**Comment by HaploX1** [comment]
The creator creates Mai. It shouldn't be there minimized at all, but directly be placed and creating Mai.
